version: '3.8'

services:
    mysql:
        # image: mysql:latest
        # command: --default-authentication-plugin=mysql_native_password
        build: ./db
        env_file: ./.env
        tty: true
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=$MYSQLDB_DATABASE
        ports:
            - "3306:3306"
        restart: always
        # volumes:
        #     - mysql:/var/lib/mysql
        #     - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
            
    web:
        build:
            context: ./web
            dockerfile: Dockerfile
        env_file: ./.env
        ports:
            - "3030:3030"
        links:
            - mysql
        environment:
            - DB_HOST=mysql
            - DB_USER=$MYSQLDB_USER
            - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
            - DB_NAME=$MYSQLDB_DATABASE
            - DB_PORT=$MYSQLDB_DOCKER_PORT
        stdin_open: true
        depends_on:
            - mysql
        restart: on-failure

# volumes: 
#     mysql:
#         driver: local