version: '3.8'

services:
    mysql:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        env_file: ./.env
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=$MYSQLDB_DATABASE
        ports:
            - 33060:3306
        volumes:
            - mysql:/var/lib/mysql
    web:
        depends_on:
            - mysql
        build: ./web
            # dockerfile: Dockerfile
        restart: unless-stopped
        env_file: ./.env
        ports:
            - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
        environment:
            - DB_HOST=mysql
            - DB_USER=$MYSQLDB_USER
            - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
            - DB_NAME=$MYSQLDB_DATABASE
            - DB_PORT=$MYSQLDB_DOCKER_PORT
        stdin_open: true
        tty: true

volumes: 
    mysql: